[package]
name = "common-utils-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { version = "2.0.18", optional = true }

[features]
default = ["env"]
env = ["thiserror"]
thiserror = ["dep:thiserror"]
